### ISSUE TITLE
Working on Heroku?

### ISSUE THREAD

**Issue by turadg** [toyokazu/omniauth_shibboleth#1]
Hi. Thanks for the wiki page on integrating this with Passenger Fusion. Do you know whether this would work on Heroku? If not, what changes would be necessary?

(also, have you thought of contributing your code as a pull request to the main repo?)

**Comment by toyokazu** [comment]
Hi. Thank you for your comment.
I am interested in Heroku but I've never tried it yet.
So thus I am sorry that  I do not know whether omniauth_shibboleth can be integrated into it or not.

If omniauth can work with Heroku, the differences between omniauth main tree and omniauth_shibboleth tree can be easily checked by the followings:

### clone omniauth_shibboleth

% git clone git://github.com/toyokazu/omniauth_shibboleth.git
% cd omniauth_shibboleth

### add original branch to track the latest updates

% git remote add intridea https://github.com/intridea/omniauth.git
% git pull intridea master

### fails to merge...

### check difference

% git diff intridea/master

Very small changes are required for using Shibboleth :)

I am also interested in contributing my code to main repo. However I've also never tried 'pull request'. I would like to check the customs (?) for 'pull request', then I will try it.

**Comment by turadg** [comment]
Thanks for the reply. I'm also experimenting with Pubcookie so I may go with that.

Regarding pull requests, they're pretty easy, but by the looks of the latest [README on omniauth](https://github.com/intridea/omniauth), it's worth waiting for their 1.0 release and releasing an `oa-shibboleth` gem separately.

**Comment by toyokazu** [comment]
I did not know the changes in omniauth 1.0. It is worth information for me to try pull requests.
Thank you again. I will check it :)
