### ISSUE TITLE
turn into an OmniAuth 1.0 strategy

### ISSUE THREAD

**Issue by turadg** [toyokazu/omniauth_shibboleth#2]
OmniAuth 1.0 has modular auth strategies:

https://github.com/intridea/omniauth/wiki/Strategy-Contribution-Guide

**Comment by toyokazu** [comment]
Thank you for your info!
It is very helpful for me.
Currently, while I could not have time to visit ;(, I will check it.
Thank you again :)

**Comment by toyokazu** [comment]
Hi,

I have implemented omniauth-shibboleth for OmniAuth 1.0. Project name is renamed based on the gem name rule (use '-').

https://github.com/toyokazu/omniauth-shibboleth

I added it to Strategy list on omniauth wiki.
https://github.com/intridea/omniauth/wiki/List-of-Strategies

I also submit pull request on on_failure fix (insert env['SCRIPT_NAME']).

Thank you for your info.

**Comment by turadg** [comment]
Cool! I hope it will also be made to work with [https://github.com/alexcrichton/rack-shibboleth] by @alexcrichton so it works in web servers besides Apache.
